### ISSUE TITLE
show the great idea at Tartu Mini Maker!

### ISSUE THREAD

**Issue by edmundlaugasson** [hitsa/candibox#2]
The news in Estonian is here - http://makerfairetartu.ee/?p=301
It says that at 20th September 2015 there will be next event at Tartu's Science Park AHHAA about self-made projects. For registering write an e-mail to makerfaire@ahhaa.ee or register directly at: https://goo.gl/qYgwjW

**Comment by borgand** [comment]
Thanks, Edmund, but I'm not sure Maker Faire is the right place to promote Candibox, not least because it is not self-made nor invented, but instead government paid project.

**Comment by edmundlaugasson** [comment]
You may ask from e-mail mentioned in first message about eligibility. If to read further event description then all designers, programmers, inventers etc are invited. I am pretty sure that some of the participants develop projects also using funding even from EU projects, also governmental, universities etc.
